#adapted from example in docker documentation
version: '3'

services:
   web:
     build: .
     volumes:
        - .:/code
     expose:
       - 8000
     user: "1002:1003" #system dependent
     command: python /code/mysite/manage.py runserver 0.0.0.0:8000
 
   nginx:
    restart: always
    build: ./nginx/
    volumes:
       - ./mysite/myapp/static:/static/
    depends_on: 
       - web
    ports:
       - 80:80
    links:
       - web:web